# 	SPDX-FileCopyrightText: 2022 Slant Tech, Dylan Wadler <dwadler@slant.tech>
#  
# 	SPDX-License-Identifier: GPL-3.0-or-later

version: "2"
plugins:
  cppcheck:
    enabled: true
    config:
      check: all
      project: compile_commands.json
      platform: unix64
      includes:
      - include/
      - imgui/
