version: "3.6"
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis-server:/data
      - ./redis.conf:/redis-stack.conf
